# Generated by Django 6.1.1 on 2026-09-21
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('accounts', '0002_developeroauthstate')]
    operations = [
        migrations.AddField(model_name='user', name='auth_provider', field=models.CharField(default='password', max_length=16)),
        migrations.CreateModel(
            name='DeveloperOAuthExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=16)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_exchanges', to='accounts.user')),
            ],
        ),
    ]
