# Generated by Django 6.1.1 on 2026-09-19 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('otp_sent', 'OTP sent'), ('otp_verified', 'OTP verified'), ('otp_failed', 'OTP verification failed'), ('oauth_succeeded', 'OAuth login succeeded'), ('oauth_failed', 'OAuth login failed')], max_length=32)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_activities', to='applications.application')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authentication_activities', to='authentication.enduser')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
