# Generated by Django 6.1.1 on 2026-09-21
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('authentication', '0003_oauthstate')]

    operations = [
        migrations.CreateModel(
            name='OAuthLoginExchange',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('provider', models.CharField(max_length=16)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_login_exchanges', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_login_exchanges', to='authentication.enduser')),
            ],
        ),
    ]
