"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY must be set in the environment.")

DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost"
).split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

        "corsheaders",
    "rest_framework",

    "accounts",
    "applications",
    "authentication",

]

MIDDLEWARE = [

    "corsheaders.middleware.CorsMiddleware",


    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://[::1]:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://[::1]:5174",
]
CORS_ALLOW_HEADERS = [
    *default_headers,
    "x-api-key",
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# Developer dashboard JWTs. These remain separate from end-user tokens below.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("DEVELOPER_ACCESS_TOKEN_MINUTES", "60"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("DEVELOPER_REFRESH_TOKEN_DAYS", "7"))),
}


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "accounts.User"


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email defaults to the console backend for local development. Configure an SMTP
# backend and credentials through environment variables for deployment.
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@localhost")

OTP_LIFETIME_MINUTES = int(os.getenv("OTP_LIFETIME_MINUTES", "5"))
OTP_RESEND_SECONDS = int(os.getenv("OTP_RESEND_SECONDS", "60"))
END_USER_TOKEN_SECRET = os.getenv("END_USER_TOKEN_SECRET", SECRET_KEY)
END_USER_TOKEN_ISSUER = os.getenv("END_USER_TOKEN_ISSUER", "authenticator")
END_USER_TOKEN_AUDIENCE = os.getenv("END_USER_TOKEN_AUDIENCE", "authenticator-end-user")
END_USER_ACCESS_TOKEN_LIFETIME = timedelta(minutes=int(os.getenv("END_USER_ACCESS_TOKEN_MINUTES", "15")))
END_USER_REFRESH_TOKEN_LIFETIME = timedelta(days=int(os.getenv("END_USER_REFRESH_TOKEN_DAYS", "7")))
OAUTH_CALLBACK_URL = os.getenv("OAUTH_CALLBACK_URL", "http://localhost:8000/api/v1/auth/oauth/{provider}/callback/")
END_USER_OAUTH_FRONTEND_URL = os.getenv("END_USER_OAUTH_FRONTEND_URL", "http://localhost:5173/oauth/callback")
DEVELOPER_OAUTH_CALLBACK_URL = os.getenv(
    "DEVELOPER_OAUTH_CALLBACK_URL",
    "http://localhost:8000/api/v1/accounts/oauth/{provider}/callback/",
)
DEVELOPER_OAUTH_FRONTEND_URL = os.getenv(
    "DEVELOPER_OAUTH_FRONTEND_URL",
    "http://localhost:5173/",
)
OAUTH_STATE_LIFETIME_MINUTES = int(os.getenv("OAUTH_STATE_LIFETIME_MINUTES", "10"))
GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", "")
GITHUB_OAUTH_CLIENT_ID = os.getenv("GITHUB_OAUTH_CLIENT_ID", "")
GITHUB_OAUTH_CLIENT_SECRET = os.getenv("GITHUB_OAUTH_CLIENT_SECRET", "")
GITHUB_DEVELOPER_CLIENT_ID = os.getenv("GITHUB_DEVELOPER_CLIENT_ID", "")
GITHUB_DEVELOPER_CLIENT_SECRET = os.getenv("GITHUB_DEVELOPER_CLIENT_SECRET", "")
